%YAML:1.0
vectorSize: 42
points_markFlag_0: 0
points_selectFlag_0: 0
points_pixel_x_0: 295
points_pixel_y_0: 173
points_pos_x_0: 0
points_pos_y_0: 0
points_markFlag_1: 0
points_selectFlag_1: 0
points_pixel_x_1: 298
points_pixel_y_1: 198
points_pos_x_1: 0
points_pos_y_1: 0
points_markFlag_2: 0
points_selectFlag_2: 0
points_pixel_x_2: 294
points_pixel_y_2: 475
points_pos_x_2: 0
points_pos_y_2: 0
points_markFlag_3: 0
points_selectFlag_3: 0
points_pixel_x_3: 74
points_pixel_y_3: 691
points_pos_x_3: 0
points_pos_y_3: 0
points_markFlag_4: 0
points_selectFlag_4: 0
points_pixel_x_4: 298
points_pixel_y_4: 725
points_pos_x_4: 0
points_pos_y_4: 0
points_markFlag_5: 0
points_selectFlag_5: 0
points_pixel_x_5: 298
points_pixel_y_5: 725
points_pos_x_5: 0
points_pos_y_5: 0
points_markFlag_6: 0
points_selectFlag_6: 0
points_pixel_x_6: 628
points_pixel_y_6: 59
points_pos_x_6: 0
points_pos_y_6: 0
points_markFlag_7: 0
points_selectFlag_7: 0
points_pixel_x_7: 532
points_pixel_y_7: 316
points_pos_x_7: 0
points_pos_y_7: 0
points_markFlag_8: 0
points_selectFlag_8: 0
points_pixel_x_8: 349
points_pixel_y_8: 481
points_pos_x_8: 0
points_pos_y_8: 0
points_markFlag_9: 0
points_selectFlag_9: 0
points_pixel_x_9: 340
points_pixel_y_9: 715
points_pos_x_9: 0
points_pos_y_9: 0
points_markFlag_10: 0
points_selectFlag_10: 0
points_pixel_x_10: 454
points_pixel_y_10: 734
points_pos_x_10: 0
points_pos_y_10: 0
points_markFlag_11: 0
points_selectFlag_11: 0
points_pixel_x_11: 436
points_pixel_y_11: 927
points_pos_x_11: 0
points_pos_y_11: 0
points_markFlag_12: 0
points_selectFlag_12: 0
points_pixel_x_12: 838
points_pixel_y_12: 155
points_pos_x_12: 0
points_pos_y_12: 0
points_markFlag_13: 0
points_selectFlag_13: 0
points_pixel_x_13: 878
points_pixel_y_13: 341
points_pos_x_13: 0
points_pos_y_13: 0
points_markFlag_14: 0
points_selectFlag_14: 0
points_pixel_x_14: 859
points_pixel_y_14: 361
points_pos_x_14: 0
points_pos_y_14: 0
points_markFlag_15: 0
points_selectFlag_15: 0
points_pixel_x_15: 956
points_pixel_y_15: 716
points_pos_x_15: 0
points_pos_y_15: 0
points_markFlag_16: 0
points_selectFlag_16: 0
points_pixel_x_16: 957
points_pixel_y_16: 730
points_pos_x_16: 0
points_pos_y_16: 0
points_markFlag_17: 0
points_selectFlag_17: 0
points_pixel_x_17: 705
points_pixel_y_17: 976
points_pos_x_17: 0
points_pos_y_17: 0
points_markFlag_18: 0
points_selectFlag_18: 0
points_pixel_x_18: 1038
points_pixel_y_18: 136
points_pos_x_18: 0
points_pos_y_18: 0
points_markFlag_19: 0
points_selectFlag_19: 0
points_pixel_x_19: 967
points_pixel_y_19: 286
points_pos_x_19: 0
points_pos_y_19: 0
points_markFlag_20: 0
points_selectFlag_20: 0
points_pixel_x_20: 1043
points_pixel_y_20: 475
points_pos_x_20: 0
points_pos_y_20: 0
points_markFlag_21: 0
points_selectFlag_21: 0
points_pixel_x_21: 961
points_pixel_y_21: 714
points_pos_x_21: 0
points_pos_y_21: 0
points_markFlag_22: 0
points_selectFlag_22: 0
points_pixel_x_22: 1098
points_pixel_y_22: 744
points_pos_x_22: 0
points_pos_y_22: 0
points_markFlag_23: 0
points_selectFlag_23: 0
points_pixel_x_23: 1252
points_pixel_y_23: 972
points_pos_x_23: 0
points_pos_y_23: 0
points_markFlag_24: 0
points_selectFlag_24: 0
points_pixel_x_24: 1419
points_pixel_y_24: 114
points_pos_x_24: 0
points_pos_y_24: 0
points_markFlag_25: 0
points_selectFlag_25: 0
points_pixel_x_25: 1379
points_pixel_y_25: 248
points_pos_x_25: 0
points_pos_y_25: 0
points_markFlag_26: 0
points_selectFlag_26: 0
points_pixel_x_26: 1384
points_pixel_y_26: 444
points_pos_x_26: 0
points_pos_y_26: 0
points_markFlag_27: 0
points_selectFlag_27: 0
points_pixel_x_27: 1466
points_pixel_y_27: 560
points_pos_x_27: 0
points_pos_y_27: 0
points_markFlag_28: 0
points_selectFlag_28: 0
points_pixel_x_28: 1362
points_pixel_y_28: 818
points_pos_x_28: 0
points_pos_y_28: 0
points_markFlag_29: 0
points_selectFlag_29: 0
points_pixel_x_29: 1500
points_pixel_y_29: 908
points_pos_x_29: 0
points_pos_y_29: 0
points_markFlag_30: 0
points_selectFlag_30: 0
points_pixel_x_30: 1625
points_pixel_y_30: 128
points_pos_x_30: 0
points_pos_y_30: 0
points_markFlag_31: 0
points_selectFlag_31: 0
points_pixel_x_31: 1721
points_pixel_y_31: 284
points_pos_x_31: 0
points_pos_y_31: 0
points_markFlag_32: 0
points_selectFlag_32: 0
points_pixel_x_32: 1674
points_pixel_y_32: 382
points_pos_x_32: 0
points_pos_y_32: 0
points_markFlag_33: 0
points_selectFlag_33: 0
points_pixel_x_33: 1767
points_pixel_y_33: 673
points_pos_x_33: 0
points_pos_y_33: 0
points_markFlag_34: 0
points_selectFlag_34: 0
points_pixel_x_34: 1770
points_pixel_y_34: 726
points_pos_x_34: 0
points_pos_y_34: 0
points_markFlag_35: 0
points_selectFlag_35: 0
points_pixel_x_35: 1849
points_pixel_y_35: 971
points_pos_x_35: 0
points_pos_y_35: 0
points_markFlag_36: 1
points_selectFlag_36: 0
points_pixel_x_36: 681
points_pixel_y_36: 453
points_pos_x_36: 2454
points_pos_y_36: 1785
points_markFlag_37: 1
points_selectFlag_37: 0
points_pixel_x_37: 696
points_pixel_y_37: 569
points_pos_x_37: 2479
points_pos_y_37: 2304
points_markFlag_38: 1
points_selectFlag_38: 0
points_pixel_x_38: 550
points_pixel_y_38: 440
points_pos_x_38: 1897
points_pos_y_38: 1653
points_markFlag_39: 1
points_selectFlag_39: 0
points_pixel_x_39: 906
points_pixel_y_39: 418
points_pos_x_39: 3453
points_pos_y_39: 1713
points_markFlag_40: 1
points_selectFlag_40: 0
points_pixel_x_40: 523
points_pixel_y_40: 539
points_pos_x_40: 1708
points_pos_y_40: 2080
points_markFlag_41: 1
points_selectFlag_41: 0
points_pixel_x_41: 999
points_pixel_y_41: 687
points_pos_x_41: 3829
points_pos_y_41: 2956
