%YAML:1.0
vectorSize: 48
points_markFlag_0: 0
points_selectFlag_0: 0
points_pixel_x_0: 286
points_pixel_y_0: 148
points_pos_x_0: 0
points_pos_y_0: 0
points_markFlag_1: 0
points_selectFlag_1: 0
points_pixel_x_1: 286
points_pixel_y_1: 148
points_pos_x_1: 0
points_pos_y_1: 0
points_markFlag_2: 0
points_selectFlag_2: 0
points_pixel_x_2: 275
points_pixel_y_2: 500
points_pos_x_2: 0
points_pos_y_2: 0
points_markFlag_3: 0
points_selectFlag_3: 0
points_pixel_x_3: 254
points_pixel_y_3: 649
points_pos_x_3: 0
points_pos_y_3: 0
points_markFlag_4: 0
points_selectFlag_4: 0
points_pixel_x_4: 257
points_pixel_y_4: 812
points_pos_x_4: 0
points_pos_y_4: 0
points_markFlag_5: 0
points_selectFlag_5: 0
points_pixel_x_5: 279
points_pixel_y_5: 945
points_pos_x_5: 0
points_pos_y_5: 0
points_markFlag_6: 0
points_selectFlag_6: 0
points_pixel_x_6: 373
points_pixel_y_6: 110
points_pos_x_6: 0
points_pos_y_6: 0
points_markFlag_7: 0
points_selectFlag_7: 0
points_pixel_x_7: 579
points_pixel_y_7: 238
points_pos_x_7: 0
points_pos_y_7: 0
points_markFlag_8: 0
points_selectFlag_8: 0
points_pixel_x_8: 353
points_pixel_y_8: 469
points_pos_x_8: 0
points_pos_y_8: 0
points_markFlag_9: 0
points_selectFlag_9: 0
points_pixel_x_9: 363
points_pixel_y_9: 605
points_pos_x_9: 0
points_pos_y_9: 0
points_markFlag_10: 0
points_selectFlag_10: 0
points_pixel_x_10: 638
points_pixel_y_10: 782
points_pos_x_10: 0
points_pos_y_10: 0
points_markFlag_11: 0
points_selectFlag_11: 0
points_pixel_x_11: 434
points_pixel_y_11: 951
points_pos_x_11: 0
points_pos_y_11: 0
points_markFlag_12: 0
points_selectFlag_12: 0
points_pixel_x_12: 434
points_pixel_y_12: 951
points_pos_x_12: 0
points_pos_y_12: 0
points_markFlag_13: 0
points_selectFlag_13: 0
points_pixel_x_13: 935
points_pixel_y_13: 308
points_pos_x_13: 0
points_pos_y_13: 0
points_markFlag_14: 0
points_selectFlag_14: 0
points_pixel_x_14: 815
points_pixel_y_14: 533
points_pos_x_14: 0
points_pos_y_14: 0
points_markFlag_15: 0
points_selectFlag_15: 0
points_pixel_x_15: 749
points_pixel_y_15: 597
points_pos_x_15: 0
points_pos_y_15: 0
points_markFlag_16: 0
points_selectFlag_16: 0
points_pixel_x_16: 644
points_pixel_y_16: 781
points_pos_x_16: 0
points_pos_y_16: 0
points_markFlag_17: 0
points_selectFlag_17: 0
points_pixel_x_17: 692
points_pixel_y_17: 969
points_pos_x_17: 0
points_pos_y_17: 0
points_markFlag_18: 0
points_selectFlag_18: 0
points_pixel_x_18: 1107
points_pixel_y_18: 162
points_pos_x_18: 0
points_pos_y_18: 0
points_markFlag_19: 0
points_selectFlag_19: 0
points_pixel_x_19: 1107
points_pixel_y_19: 162
points_pos_x_19: 0
points_pos_y_19: 0
points_markFlag_20: 0
points_selectFlag_20: 0
points_pixel_x_20: 1271
points_pixel_y_20: 538
points_pos_x_20: 0
points_pos_y_20: 0
points_markFlag_21: 0
points_selectFlag_21: 0
points_pixel_x_21: 1263
points_pixel_y_21: 570
points_pos_x_21: 0
points_pos_y_21: 0
points_markFlag_22: 1
points_selectFlag_22: 0
points_pixel_x_22: 1099
points_pixel_y_22: 804
points_pos_x_22: 3590
points_pos_y_22: 846
points_markFlag_23: 0
points_selectFlag_23: 0
points_pixel_x_23: 1118
points_pixel_y_23: 910
points_pos_x_23: 0
points_pos_y_23: 0
points_markFlag_24: 0
points_selectFlag_24: 0
points_pixel_x_24: 1424
points_pixel_y_24: 179
points_pos_x_24: 0
points_pos_y_24: 0
points_markFlag_25: 0
points_selectFlag_25: 0
points_pixel_x_25: 1424
points_pixel_y_25: 179
points_pos_x_25: 0
points_pos_y_25: 0
points_markFlag_26: 0
points_selectFlag_26: 0
points_pixel_x_26: 1392
points_pixel_y_26: 434
points_pos_x_26: 0
points_pos_y_26: 0
points_markFlag_27: 0
points_selectFlag_27: 0
points_pixel_x_27: 1591
points_pixel_y_27: 629
points_pos_x_27: 0
points_pos_y_27: 0
points_markFlag_28: 1
points_selectFlag_28: 0
points_pixel_x_28: 1300
points_pixel_y_28: 861
points_pos_x_28: 4460
points_pos_y_28: 1011
points_markFlag_29: 0
points_selectFlag_29: 0
points_pixel_x_29: 1569
points_pixel_y_29: 900
points_pos_x_29: 0
points_pos_y_29: 0
points_markFlag_30: 0
points_selectFlag_30: 0
points_pixel_x_30: 1617
points_pixel_y_30: 143
points_pos_x_30: 0
points_pos_y_30: 0
points_markFlag_31: 0
points_selectFlag_31: 0
points_pixel_x_31: 1631
points_pixel_y_31: 317
points_pos_x_31: 0
points_pos_y_31: 0
points_markFlag_32: 0
points_selectFlag_32: 0
points_pixel_x_32: 1602
points_pixel_y_32: 362
points_pos_x_32: 0
points_pos_y_32: 0
points_markFlag_33: 0
points_selectFlag_33: 0
points_pixel_x_33: 1678
points_pixel_y_33: 695
points_pos_x_33: 0
points_pos_y_33: 0
points_markFlag_34: 0
points_selectFlag_34: 0
points_pixel_x_34: 1600
points_pixel_y_34: 738
points_pos_x_34: 0
points_pos_y_34: 0
points_markFlag_35: 0
points_selectFlag_35: 0
points_pixel_x_35: 1603
points_pixel_y_35: 1012
points_pos_x_35: 0
points_pos_y_35: 0
points_markFlag_36: 1
points_selectFlag_36: 0
points_pixel_x_36: 821
points_pixel_y_36: 1007
points_pos_x_36: 2453
points_pos_y_36: 1854
points_markFlag_37: 1
points_selectFlag_37: 0
points_pixel_x_37: 481
points_pixel_y_37: 911
points_pos_x_37: 995
points_pos_y_37: 1434
points_markFlag_38: 1
points_selectFlag_38: 0
points_pixel_x_38: 990
points_pixel_y_38: 584
points_pos_x_38: 3065
points_pos_y_38: 32823
points_markFlag_39: 1
points_selectFlag_39: 0
points_pixel_x_39: 470
points_pixel_y_39: 468
points_pos_x_39: 875
points_pos_y_39: 33174
points_markFlag_40: 1
points_selectFlag_40: 0
points_pixel_x_40: 768
points_pixel_y_40: 484
points_pos_x_40: 2126
points_pos_y_40: 33227
points_markFlag_41: 1
points_selectFlag_41: 0
points_pixel_x_41: 1275
points_pixel_y_41: 457
points_pos_x_41: 4214
points_pos_y_41: 33488
points_markFlag_42: 1
points_selectFlag_42: 0
points_pixel_x_42: 1360
points_pixel_y_42: 423
points_pos_x_42: 4558
points_pos_y_42: 33662
points_markFlag_43: 1
points_selectFlag_43: 0
points_pixel_x_43: 1299
points_pixel_y_43: 635
points_pos_x_43: 4356
points_pos_y_43: 33
points_markFlag_44: 1
points_selectFlag_44: 0
points_pixel_x_44: 1024
points_pixel_y_44: 1012
points_pos_x_44: 3323
points_pos_y_44: 1819
points_markFlag_45: 1
points_selectFlag_45: 0
points_pixel_x_45: 908
points_pixel_y_45: 889
points_pos_x_45: 2808
points_pos_y_45: 1235
points_markFlag_46: 1
points_selectFlag_46: 0
points_pixel_x_46: 1505
points_pixel_y_46: 899
points_pos_x_46: 5334
points_pos_y_46: 1044
points_markFlag_47: 1
points_selectFlag_47: 0
points_pixel_x_47: 1403
points_pixel_y_47: 828
points_pos_x_47: 4873
points_pos_y_47: 765
